//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.12 at 02:29:42 PM IST 
//


package com.tbb.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TestCases" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TestSteps" type="{}testStepType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="testID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nID" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="perspective" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testCases"
})
@XmlRootElement(name = "TestData")
public class TestData {

    @XmlElement(name = "TestCases", required = true)
    protected List<TestData.TestCases> testCases;

    /**
     * Gets the value of the testCases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestData.TestCases }
     * 
     * 
     */
    public List<TestData.TestCases> getTestCases() {
        if (testCases == null) {
            testCases = new ArrayList<TestData.TestCases>();
        }
        return this.testCases;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TestSteps" type="{}testStepType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="testID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nID" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="perspective" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testSteps"
    })
    public static class TestCases {

        @XmlElement(name = "TestSteps", required = true)
        protected List<TestStepType> testSteps;
        @XmlAttribute
        protected String testID;
        @XmlAttribute(name = "nID")
        protected Integer nid;
        @XmlAttribute
        protected Integer perspective;
        @XmlAttribute
        protected String description;

        /**
         * Gets the value of the testSteps property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testSteps property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestSteps().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestStepType }
         * 
         * 
         */
        public List<TestStepType> getTestSteps() {
            if (testSteps == null) {
                testSteps = new ArrayList<TestStepType>();
            }
            return this.testSteps;
        }

        /**
         * Gets the value of the testID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTestID() {
            return testID;
        }

        /**
         * Sets the value of the testID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTestID(String value) {
            this.testID = value;
        }

        /**
         * Gets the value of the nid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNID() {
            return nid;
        }

        /**
         * Sets the value of the nid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNID(Integer value) {
            this.nid = value;
        }

        /**
         * Gets the value of the perspective property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPerspective() {
            return perspective;
        }

        /**
         * Sets the value of the perspective property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPerspective(Integer value) {
            this.perspective = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }

}
